# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9138029908cf46930654f1b220342be1"
name = "backup-shop"
handle = "backup-shop"
application_url = "https://hiking-wearing-listing-solved.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "trialproject12.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://hiking-wearing-listing-solved.trycloudflare.com/auth/callback",
  "https://hiking-wearing-listing-solved.trycloudflare.com/auth/shopify/callback",
  "https://hiking-wearing-listing-solved.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
