# Generated by Django 4.2.11 on 2024-03-29 08:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('organization_name', models.CharField(max_length=100)),
                ('store_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('Product', 'product'), ('Order', 'order'), ('type3', 'Type 3')], max_length=10)),
                ('data', models.JSONField()),
                ('version', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('backup_date', models.DateField(default=datetime.date(2024, 3, 29))),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.store')),
            ],
        ),
    ]
