# Generated by Django 4.2.11 on 2024-03-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='product_id',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
