# Generated by Django 4.2.11 on 2024-03-29 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='version',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
