# Generated by Django 4.2.11 on 2024-03-31 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_alter_object_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='version',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='object',
            name='backup_date',
            field=models.DateField(default=datetime.date(2024, 3, 31)),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_type',
            field=models.CharField(choices=[('products', 'products'), ('orders', 'orders'), ('themes', 'themes')], max_length=10),
        ),
    ]
