# Generated by Django 4.2.11 on 2024-03-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_rename_version_object_uuid_alter_object_backup_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='object_type',
            field=models.CharField(choices=[('products', 'products'), ('orders', 'orders'), ('themes', 'themes'), ('pages', 'pages'), ('custom_collections', 'custom_collections'), ('smart_collections', 'smart_collections')], max_length=50),
        ),
    ]
