# Generated by Django 4.2.11 on 2024-04-02 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_alter_object_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='backup_date',
            field=models.DateField(default=datetime.date(2024, 4, 2)),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_type',
            field=models.CharField(choices=[('products', 'products'), ('orders', 'orders'), ('themes', 'themes'), ('pages', 'pages'), ('custom_collections', 'custom_collections'), ('smart_collections', 'smart_collections'), ('locations', 'locations'), ('policies', 'policies'), ('shipping_zones', 'shipping_zones'), ('customers', 'customers'), ('blogs', 'blogs'), ('images', 'images'), ('theme_assets', 'theme_assets'), ('saved_searchs', 'saved_search'), ('metafields', 'metafields'), ('files', 'files')], max_length=50),
        ),
    ]
