# Generated by Django 4.2.11 on 2024-04-28 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_alter_object_backup_date_alter_object_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='backup_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_type',
            field=models.CharField(choices=[('products', 'products'), ('orders', 'orders'), ('themes', 'themes'), ('pages', 'pages'), ('custom_collections', 'custom_collections'), ('smart_collections', 'smart_collections'), ('locations', 'locations'), ('policies', 'policies'), ('shipping_zones', 'shipping_zones'), ('customers', 'customers'), ('blogs', 'blogs'), ('inventory_levels', 'inventory_levels'), ('saved_searches', 'saved_searches'), ('files', 'files')], max_length=50),
        ),
    ]
