# Generated by Django 4.2.11 on 2024-04-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_alter_object_backup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='backup_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
