# Generated by Django 4.2.11 on 2024-04-29 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_alter_object_backup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='backup_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
